using PragmaticScaffolder.Application;
using PragmaticScaffolder.Application.Abstractions;

namespace PragmaticScaffolder.Infrastructure.FileSystem;

/// <summary>Writes generated files to disk, skipping files a developer has customised.</summary>
public sealed class FileSystemGeneratedFileWriter : IGeneratedFileWriter
{
    public void Write(string outputPath, IReadOnlyList<GeneratedFile> files, List<string> errors)
    {
        foreach (var file in files)
        {
            try
            {
                var fullPath = Path.Combine(outputPath, file.RelativePath.Replace('/', Path.DirectorySeparatorChar));
                Directory.CreateDirectory(Path.GetDirectoryName(fullPath)!);

                // Skip files the developer has customised (no auto-generated header)
                if (File.Exists(fullPath))
                {
                    var firstLine = File.ReadLines(fullPath).FirstOrDefault() ?? string.Empty;
                    if (!firstLine.Contains("<auto-generated />"))
                        continue;
                }

                File.WriteAllText(fullPath, file.Content);
            }
            catch (Exception ex)
            {
                errors.Add($"Failed writing '{file.RelativePath}': {ex.Message}");
            }
        }
    }
}
